schema_version = "1.0.0"
id = "blender_to_godot_pipeline"
version = "0.1.0"
name = "Blender to Godot Pipeline"
tagline = "Assign Godot Node classes and variables from Blender"
maintainer = "Nathan Zimmer"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
website = "https://github.com/NathanZimmer/blender_to_godot_pipeline"